# This workflows will create a standalone executable for mac os 11.

name: Create Standalone (mac OS 11)

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry

    - name: Create executable
      run: |
        python -m venv .venv
        . .venv/bin/activate
        python -m pip install --upgrade pip
        pip install .
        pip install pyinstaller doit pillow
        doit prepare_build -y
        pyinstaller pyinstaller.spec --onefile
        ls dist
        


